<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPUpQUw7\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPUpQUw7/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPUpQUw7.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPUpQUw7\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerPUpQUw7\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'PUpQUw7',
    'container.build_id' => 'ec869d25',
    'container.build_time' => 1516875405,
));
